version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    restart: on-failure
    environment: 
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - HOST=${HOST}
      - DATABASE_DIALECT=${DATABASE_DIALECT}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NATIVE=${DATABASE_NATIVE}
      - DATABASE_SYNC=${DATABASE_SYNC}
    ports:
      - "3000:3000"
    links:
      - pgsql-db
    networks:
      - zubut-network
    depends_on:
      - pgsql-db

  pgsql-db:
    image: postgres:13
    container_name: pgsql-db
    restart: unless-stopped
    environment: 
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports: 
      - "5432:5432"
    networks: 
      - zubut-network

networks: 
  zubut-network:
    driver: bridge